networks:
  javaguru:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - javaguru
    depends_on:
      - frontend
      - insurance-calculator-app
      - black-list-app
      - doc-generator-app
  frontend:
    build:
      context: ./calc-frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    networks: [ javaguru ]
    ports:
      - "8083:8080"
  message-broker:
    networks: [ javaguru ]
    container_name: rabbitmq-container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 10s
      retries: 5

  db:

    networks: [ javaguru ]
    container_name: postgresql-container
    image: postgres:16
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: userpass
      POSTGRES_MULTIPLE_DATABASES: insurance_calculator_db,black_list_db
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/init/01-create-databases.sql:/docker-entrypoint-initdb.d/01-create-databases.sql
      - ./postgresql/init/02-create-users.sql:/docker-entrypoint-initdb.d/02-create-users.sql

  insurance-calculator-app:
    networks: [ javaguru ]
    build: ./insurance-calculator-app
    container_name: insurance-calc-container
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: insurance_calculator_db
      DB_USER: appuser
      DB_PASSWORD: userpass
    ports:
      - "8080:8080"
    depends_on:
      - message-broker
      - db

  black-list-app:
    networks: [ javaguru ]
    build: ./black-list-app
    container_name: black-list-container
    environment:
      SPRING_PROFILES_ACTIVE: "postgresql-container"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: black_list_db
      DB_USER: appuser
      DB_PASSWORD: userpass
    ports:
      - "8081:8080"
    depends_on:
      - message-broker
      - db

  doc-generator-app:
    networks: [ javaguru ]
    build: ./doc-generator-app
    container_name: doc-generator-container
    image: doc-generator:1.0.2
    volumes:
      - ./doc-generator-app/docs/proposals:/app/docs/proposals
    ports:
      - "8082:8080"
    depends_on:
      - message-broker
volumes:
  pgdata:
