CREATE TABLE IF NOT EXISTS MEDICAL_RISK_LIMIT_LEVEL (
    MEDICAL_RISK_LIMIT_LEVEL_IC VARCHAR(20) PRIMARY KEY,
    COEFFICIENT DECIMAL(5, 2) NOT NULL
);

INSERT INTO MEDICAL_RISK_LIMIT_LEVEL (MEDICAL_RISK_LIMIT_LEVEL_IC, COEFFICIENT)
SELECT 'LEVEL_10000', 1.0
WHERE NOT EXISTS (SELECT 1 FROM MEDICAL_RISK_LIMIT_LEVEL WHERE MEDICAL_RISK_LIMIT_LEVEL_IC = 'LEVEL_10000');

INSERT INTO MEDICAL_RISK_LIMIT_LEVEL (MEDICAL_RISK_LIMIT_LEVEL_IC, COEFFICIENT)
SELECT 'LEVEL_15000', 1.2
WHERE NOT EXISTS (SELECT 1 FROM MEDICAL_RISK_LIMIT_LEVEL WHERE MEDICAL_RISK_LIMIT_LEVEL_IC = 'LEVEL_15000');

INSERT INTO MEDICAL_RISK_LIMIT_LEVEL (MEDICAL_RISK_LIMIT_LEVEL_IC, COEFFICIENT)
SELECT 'LEVEL_20000', 1.5
WHERE NOT EXISTS (SELECT 1 FROM MEDICAL_RISK_LIMIT_LEVEL WHERE MEDICAL_RISK_LIMIT_LEVEL_IC = 'LEVEL_20000');

INSERT INTO MEDICAL_RISK_LIMIT_LEVEL (MEDICAL_RISK_LIMIT_LEVEL_IC, COEFFICIENT)
SELECT 'LEVEL_50000', 2.0
WHERE NOT EXISTS (SELECT 1 FROM MEDICAL_RISK_LIMIT_LEVEL WHERE MEDICAL_RISK_LIMIT_LEVEL_IC = 'LEVEL_50000');
